crm/urls.py
from django.conf.urls import patterns, url
from crm import views as v



urlpatterns = patterns(
    '',
    url(r'^(?P<model>(:?company))/list/$', v.List.as_view(), name='list'),
    url(r'^(?P<model>(:?requirement))/list/(?P<pk>.*)$', v.List.as_view(), name='list'),
    url(r'^(?P<model>(:?company))/create/$', v.Create.as_view(), name='create'),
    url(r'^(?P<model>(:?requirement))/create/(?P<pk>.*)/$', v.Create.as_view(), name='create'),
    url(r'^(?P<model>(:?company|requirement))/update/(?P<pk>\d+)/$', v.Update.as_view(), name='update'),
    url(r'^(?P<model>(:?company|requirement))/delete/(?P<pk>\d+)/$', v.Delete.as_view(), name='update'),
    url(r'^(?P<model>(:?company|requirement))/status/(?P<pk>\d+)/$', v.Status.as_view(), name='update'),

    url(r'^(?P<model>(:?profile|employeeinfo))/list/$', v.List.as_view(), name='list'),
    url(r'^(?P<model>(:?profile|employeeinfo))/create/$', v.Create.as_view(), name='create'),
    url(r'^(?P<model>(:?profile|employeeinfo))/status/(?P<pk>\d+)/$', v.Status.as_view(), name='create'),
    url(r'^(?P<model>(:?profile|employeeinfo))/update/(?P<pk>\d+)/$', v.Update.as_view(), name='create'),
)

dsmanagement/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from crm import urls as crm



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dsmanagement.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^masterdata/', include(crm)),
    url(r'^admin/', include(admin.site.urls)),  
    url(r'^logout/$','users.user_logout',name="home"),
	url(r'^$','users.user_login',name="home"),
    url(r'^home/$','crm.views.home',name="home"),
    url(r'^org-list/$','crm.views.org_list',name="home"),
    url(r'^sales-list/$','crm.views.sales',name="home"),
    url(r'^company-list/$','crm.views.company_list',name="home"),
    url(r'^company_info/(?P<pid>\d+)$','crm.views.company_info',name="home"),
    url(r'^recur_info/$','crm.views.recur_info',name='home'),
    url(r'^recur_info/(?P<model>(:?open|inprogress|close))/(?P<pid>\d+)$','crm.views.recur_info_data',name="home"),
    url(r'^resume_save/(?P<pid>\d+)$','crm.views.resume_save',name="home"),
    url(r'^log-file/$','crm.views.log_file',name="home"),
    url(r'^production-create/$','crm.views.production_data',name="home"),
    url(r'^production-list/$','crm.views.production_list',name="home"),

    
)

crm/models.py
from __future__ import division
from django.db import models


# Create your models here.










ACTIVE = ((0,'Inactive'), (2, 'Active'),)
class Base(models.Model):
    
    """ Basic Fields """

    active = models.PositiveIntegerField(choices = ACTIVE, default=2)
    created_on = models.DateTimeField(auto_now_add = True)
    modified_on = models.DateTimeField(auto_now = True)

    def switch(self):
        self.active = {0: 2, 2: 0}[self.active]
        self.save()
        return self.active

    class Meta:
        abstract = True



class OrgInfo(Base):
    customer_name = models.CharField(max_length=200,blank=True, null=True)
    customer_created = models.DateField(blank=True, null=True)
    no_of_profile  = models.IntegerField(blank=True,null=True)
    no_of_donation = models.IntegerField(blank=True,null=True)
    total_amount = models.IntegerField(blank=True,null=True)
    sub_domain = models.CharField(max_length=200,blank=True,null=True)
    def __unicode__(self):
        return self.customer_name






class Profile(Base):

    ACTIVE_CHOICES = ((0, 'Male'), (2, 'Female'),)

    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    gender = models.PositiveIntegerField(
        choices=ACTIVE_CHOICES, blank=True, null=True)
    blood_group = models.CharField(max_length=100, blank=True, null=True)
    current_address = models.CharField(max_length=100, blank=True, null=True)
    permanet_address = models.CharField(max_length=100, blank=True, null=True)
    joining_date = models.DateField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(max_length=100, blank=True, null=True)
    mobile_number = models.IntegerField(blank=True, null=True)
    landline_number = models.IntegerField(blank=True, null=True,)
    voter_id = models.CharField(max_length=100, blank=True, null=True)
    driving_license = models.CharField(max_length=100, blank=True, null=True)
    aadhar_card = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.first_name




class EmployeeInfo(Base):
    employee_id = models.CharField(max_length=100, blank=True, null=True)
    working_shift = models.CharField(max_length=100, blank=True, null=True)
    login_time = models.TimeField(blank=True, null=True)
    logout_time = models.TimeField(blank=True, null=True)
    employee_role = models.CharField(max_length=100, blank=True, null=True)
    under_supervision = models.CharField(max_length=100, blank=True, null=True)
    break_time = models.TimeField(blank=True, null=True)
    over_time = models.TimeField(blank=True, null=True)
    total_working_hour_per_day = models.IntegerField(blank=True, null=True)
    def __unicode__(self):
        return self.employee_id







class Production(Base):
    kg = models.IntegerField(max_length=100, blank=True, null=True)
    date = models.DateField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return '%s'%(self.kg)

    def total_loss(self):
        # from __future__ import division
        return round((7/100)*self.kg)

    def yarn_output(self):
        return round((93/100)*self.kg)










class Company(Base):

    name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    type_of_company = models.CharField(max_length=100, blank=True, null=True)       
    
    def __unicode__(self):
        return self.name




cur_status = ((0,'open'),(1,'In progress'),(2,'closed'))

class Requirement(Base):
    current_status = models.IntegerField(choices = cur_status, blank = True, null = True)
    company = models.ForeignKey(Company, blank=True, null=True)
    position = models.CharField(max_length=100, blank=True, null=True)
    no_openings = models.CharField(max_length=100, blank=True, null=True)
    technology = models.CharField(max_length=100, blank=True, null=True)
    skills = models.CharField(max_length=100, blank=True, null=True)
    experience = models.CharField(max_length=100, blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    type_of_opening = models.CharField(max_length=100, blank=True, null=True)
    salary_range = models.CharField(max_length=100, blank=True, null=True)
    unique_id = models.CharField(null=True, max_length=100, unique=True)
    resume = models.FileField(upload_to='static/resume/img/%Y/%m/%d',blank=True, null=True)
    def __unicode__(self):
        return self.position

templates/masterdata/add-edit.html
{% extends "base.html" %}
{% block midpart %}


<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>


<script type="text/javascript" src="/static/js/jquery.datepick.js"></script>





<style type="text/css">
    
.error{
    width: 181px;
    color: red;
}

</style>


<script>







$(function(){


    $('#ngo_form').validate({

        rules : {
            first_name : {
            required:true
            },

            gender : {
            required:true
            },


            blood_group:{
                required:true
            },

            current_address:{
                required:true
            },


            permanet_address:{
                required:true
            },


            joining_date:{
                required:true
            },


            date_of_birth:{
                required:true
            },


            mobile_number:{
                required:true
            },


            landline_number:{
                required:true
            },



            voter_id:{
                required:true
            },


            driving_license:{
                required:true
            },


            aadhar_cards:{
                required:true
            },







            last_name: {
            email : true,
            required:true,
            },

            phone:{
                required:true,
                digits: true,
                minlength:10,
                maxlength:10
            },

            description:{
                required:true
            },

        }
    });
});


</script>









<div id="content" class="col-lg-10 col-sm-10">
            <!-- content starts -->
            <div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>

<!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form Elements</h2>
            </div>
            <div class="box-content">
				<form id="ngo_form" action="#" method = "post">{% csrf_token %}
					 {% if error %}
						<p style="color:red">
						<b>{{error}}</b>
						</p>
						{% endif %} {% for field in form %}


					 <div class="input-group col-md-4">
					 	 {{ field.label_tag }}{% if field.field.required %} <b>*</b>{% endif %} <br/> {{ field }}
					 	  <p style="color:red">{% if field.errors %}{{ field.errors|striptags }}{% endif %}</p>
				     </div>
					 	    {% endfor %} 

					 	    <br>
                    <input type="text" id="datepicker">
				     <button type="submit" class="btn btn-default">{% if edit %}Update{% else %}Submit{% endif %}</button>
				     <button type="button" class="btn close-fancybox btn-default">Cancel</button> 
				</form>
            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->

    <!-- content ends -->
    </div>



























{% endblock %}

templates/masterdata/production_add.html
{% extends "base.html" %}
{% block midpart %}




<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>



<style type="text/css">
    
.error{
    width: 181px;
    color: red;
}

</style>





<script>

$(function(){


    $('#product_form').validate({

        rules : {
            kg : {
            required:true
            },

            date : {
            required:true
            },

        }
    });
});


</script>








<div id="content" class="col-lg-10 col-sm-10">
            <!-- content starts -->
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#">Forms</a>
        </li>
    </ul>
</div>

<!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-edit"></i> Form Elements</h2>
            </div>
            <div class="box-content">
                    <form id="product_form" action="#" method = "post" enctype="multipart/form-data">{% csrf_token %}

                     <div class="input-group col-md-4">
                         <label for="id_first_name">KG:</label> <br/> <input id="id_first_name" maxlength="100" name="kg" type="number" />
                          <p style="color:red"></p>
                     </div>
                            


                     <div class="input-group col-md-4">
                         <label for="id_last_name">Date:</label> <br/> <input id="id_last_name" maxlength="100" name="date" type="text" />
                          <p style="color:red"></p>
                     </div>


                    <div class="input-group col-md-4">
                    <button type="submit" class="btn btn-default">Submit</button>
                    <button type="button" class="btn close-fancybox btn-default">Cancel</button>
                    </div>
                    </form>
            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->

    <!-- content ends -->
</div>  



{% endblock %}

templates/masterdata/production_list.html
{% extends "base.html" %}


{% block midpart %}











        <div id="content" class="col-lg-10 col-sm-10">
            <!-- content starts -->
                <div>
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Tables</a>
            </li>
        </ul>
    </div>




    <div class="row">
    <div class="box col-md-12">
    <div class="box-inner">
    <div class="box-header well" data-original-title="">
        <h2><i class="glyphicon glyphicon-user"></i> Production Process</h2>

        <div class="box-icon">
            <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
            <a href="#" class="btn btn-minimize btn-round btn-default"><i
                    class="glyphicon glyphicon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
        </div>
    </div>
    <div class="box-content">
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
    <tr>
        <th>KG</th>
        <th>Date</th>
        <th>Total Loss</th>
        <th>Yarn Output</th>

<!--        <th>Status</th>-->
<!--        <th>Action</th>-->
    </tr>
    </thead>
    <tbody>

    {% for i in obj %}
    <tr>
        <td class="center">{{i.kg}}</td>
        <td class="center">{{i.date}}</td>
        <td class="center">{{i.total_loss}}</td>
        <td class="center">{{i.yarn_output}}</td>
    </tr>
    {% endfor %}
        <td class="center">Total  Production:{{total}}</td>
        <td></td>
        <td class="center">Total Amount Loss:{{loss}}</td>
        <td class="center">{{yarn}}</td>

    </tbody>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->










{% endblock %}